In [36]:
import torch

In [37]:
# 1. Создайте случайный FloatTensor размера 3x4x5
a = torch.randn(3, 4, 5)
print(a)
print(a.type())

tensor([[[-9.6811e-01,  1.1483e+00, -1.8008e+00,  1.8089e+00, -6.8157e-01],
         [-1.4562e+00,  7.6351e-02, -8.1602e-01,  1.2502e+00, -3.6049e-01],
         [-4.4067e-01, -2.2326e-01, -7.9747e-01, -4.4097e-01, -1.0163e+00],
         [-2.8093e-01,  1.4863e+00,  1.3265e+00, -4.9614e-04,  3.8639e-01]],

        [[ 1.4239e-01, -7.8925e-01,  2.4543e-01,  1.2144e+00, -2.5893e-01],
         [-3.2052e-01, -8.0784e-01, -2.4735e-02,  2.1876e-01, -1.9688e+00],
         [-1.7050e+00, -1.4219e+00,  6.6746e-01, -8.7749e-01,  1.0235e+00],
         [-1.1418e+00,  1.4046e-01,  1.0968e+00, -8.8371e-02,  4.6164e-02]],

        [[-4.3483e-01,  1.9126e-01, -1.4230e+00, -5.6469e-01, -3.2939e-01],
         [ 6.9591e-01, -5.8190e-01,  8.0135e-01,  2.0827e-02, -5.2074e-01],
         [ 1.5452e-01,  3.7755e-01,  1.1621e+00,  2.2857e-01, -7.4248e-01],
         [ 3.0713e-01, -2.5525e-01, -1.5036e-01,  5.1168e-01,  8.4167e-01]]])
torch.FloatTensor


In [38]:
# 2. Выведите его форму (shape)
print(a.shape)

torch.Size([3, 4, 5])


In [39]:
# 3. Приведите его к форме 6х10
b = a.reshape(6, 10)
print(b)
print(b.shape)

tensor([[-9.6811e-01,  1.1483e+00, -1.8008e+00,  1.8089e+00, -6.8157e-01,
         -1.4562e+00,  7.6351e-02, -8.1602e-01,  1.2502e+00, -3.6049e-01],
        [-4.4067e-01, -2.2326e-01, -7.9747e-01, -4.4097e-01, -1.0163e+00,
         -2.8093e-01,  1.4863e+00,  1.3265e+00, -4.9614e-04,  3.8639e-01],
        [ 1.4239e-01, -7.8925e-01,  2.4543e-01,  1.2144e+00, -2.5893e-01,
         -3.2052e-01, -8.0784e-01, -2.4735e-02,  2.1876e-01, -1.9688e+00],
        [-1.7050e+00, -1.4219e+00,  6.6746e-01, -8.7749e-01,  1.0235e+00,
         -1.1418e+00,  1.4046e-01,  1.0968e+00, -8.8371e-02,  4.6164e-02],
        [-4.3483e-01,  1.9126e-01, -1.4230e+00, -5.6469e-01, -3.2939e-01,
          6.9591e-01, -5.8190e-01,  8.0135e-01,  2.0827e-02, -5.2074e-01],
        [ 1.5452e-01,  3.7755e-01,  1.1621e+00,  2.2857e-01, -7.4248e-01,
          3.0713e-01, -2.5525e-01, -1.5036e-01,  5.1168e-01,  8.4167e-01]])
torch.Size([6, 10])


In [40]:
# 4. Создайте случайный IntTensor размера 10
c = torch.randint(20, size = (10, ))
c = c.int()
print(c)
print(c.type())

tensor([15, 11,  5, 12,  3, 12,  6,  0,  7, 14], dtype=torch.int32)
torch.IntTensor


In [41]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
d = c * b
print(d)
print(d.shape)

tensor([[-1.4522e+01,  1.2631e+01, -9.0042e+00,  2.1707e+01, -2.0447e+00,
         -1.7475e+01,  4.5810e-01, -0.0000e+00,  8.7516e+00, -5.0468e+00],
        [-6.6100e+00, -2.4559e+00, -3.9874e+00, -5.2916e+00, -3.0489e+00,
         -3.3712e+00,  8.9177e+00,  0.0000e+00, -3.4730e-03,  5.4094e+00],
        [ 2.1359e+00, -8.6818e+00,  1.2272e+00,  1.4573e+01, -7.7679e-01,
         -3.8462e+00, -4.8471e+00, -0.0000e+00,  1.5313e+00, -2.7563e+01],
        [-2.5574e+01, -1.5641e+01,  3.3373e+00, -1.0530e+01,  3.0706e+00,
         -1.3702e+01,  8.4278e-01,  0.0000e+00, -6.1859e-01,  6.4630e-01],
        [-6.5225e+00,  2.1039e+00, -7.1150e+00, -6.7763e+00, -9.8818e-01,
          8.3510e+00, -3.4914e+00,  0.0000e+00,  1.4579e-01, -7.2903e+00],
        [ 2.3177e+00,  4.1530e+00,  5.8107e+00,  2.7428e+00, -2.2275e+00,
          3.6856e+00, -1.5315e+00, -0.0000e+00,  3.5817e+00,  1.1783e+01]])
torch.Size([6, 10])


In [42]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
e = torch.matmul(b, torch.transpose(b, 0, 1))
print(e)
print(e.shape)

tensor([[13.7209,  0.8016,  2.2956, -2.8178,  0.9082, -0.8971],
        [ 0.8016,  6.3041, -2.2589,  1.8856,  1.6689, -0.7655],
        [ 2.2956, -2.2589,  6.9252, -0.1722,  0.0944, -0.9546],
        [-2.8178,  1.8856, -0.1722,  9.7281, -0.3453, -1.5429],
        [ 0.9082,  1.6689,  0.0944, -0.3453,  4.4146, -1.7191],
        [-0.8971, -0.7655, -0.9546, -1.5429, -1.7191,  3.2728]])
torch.Size([6, 6])


In [43]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)
y = x**3 + z -75*t
y.backward([x, z, t])
print(x.grad, z.grad, t.grad)

tensor([3.]) tensor([1.]) tensor([-75.])


In [44]:
# 8. Создайте единичный тензор размера 5x6
f = torch.ones(5, 6)
print(f)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [45]:
# 9. Переведите его в формат numpy
f.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)